version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    volumes:
      - .:/var/www
    networks:
      - symfony

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "54321:5432"
    networks:
      - symfony

  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - symfony

networks:
  symfony:

volumes:
  database_data:
